# Configuration de l'application Spring Boot
# Port HTTP
server.port=2020

# Contexte de base de l'application
server.servlet.context-path=/api-rest

# Configuration du logging
logging.level.org.springframework.web=INFO
logging.level.tpspringrest=DEBUG

# Configuration pour le format JSON
spring.jackson.serialization.indent_output=true

# Configuration pour le format XML (optionnel)
# spring.xml.ignore=false

# Configuration pour Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/static/
spring.thymeleaf.suffix=.html
